services:
  - type: web
    name: acme-config-api
    runtime: node
    region: oregon # e.g., oregon, frankfurt
    plan: free # or standard
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        value: your-project-id
      - key: FIREBASE_PRIVATE_KEY_ID
        value: your-private-key-id
      - key: FIREBASE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n"
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-xxxxx@your-project.iam.gserviceaccount.com
      - key: FIREBASE_CLIENT_ID
        value: your-client-id
      - key: MOBILE_API_KEY
        value: your-secret-mobile-api-key-minimum-32-characters-long
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com 