services:
  # Redis Service - Option 1: Render Redis (Recommended)
  - type: redis
    name: acme-config-redis
    region: oregon
    plan: starter # $7/month - or "free" if available
    maxmemoryPolicy: allkeys-lru
    ipAllowList: [] # Allow all IPs
    
  # Web Service  
  - type: web
    name: acme-config-api
    runtime: node
    region: oregon # e.g., oregon, frankfurt
    plan: free # or standard
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: your-project-id
      - key: FIREBASE_PRIVATE_KEY_ID
        value: your-private-key-id
      - key: FIREBASE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n"
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-xxxxx@your-project.iam.gserviceaccount.com
      - key: FIREBASE_CLIENT_ID
        value: your-client-id
      - key: MOBILE_API_KEY
        value: your-secret-mobile-api-key-minimum-32-characters-long
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
      # Redis Configuration - Option 1: Render Redis
      - key: REDIS_URL
        fromService:
          type: redis
          name: acme-config-redis
          property: connectionString
      # 
      # Alternative Redis Options (comment out the above and use one of these):
      # 
      # Option 2: Redis Cloud (Free tier available)
      # - key: REDIS_URL
      #   value: redis://default:password@redis-12345.c1.us-east1-2.gce.cloud.redislabs.com:12345
      #
      # Option 3: Upstash Redis (Free tier: 10k commands/day)
      # - key: REDIS_URL  
      #   value: redis://default:password@region-redis.upstash.io:6379
      #
      # Option 4: Railway Redis (if you migrate to Railway)
      # - key: REDIS_URL
      #   value: redis://default:password@containers-us-west-1.railway.app:6379 